### PR TITLE
Master

### PR DESCRIPTION
**Pull request by matyushkins**

### CODE REVIEW

**Review by SamyDgz — APPROVED** [review]

**Comment by Godspolicy** [comment]
hi

**Review by nehtech9 — APPROVED** [review]

**Comment by Zennn11zen11** [comment]
https://app.binance.com/uni-qr/cpro/Square-Creator-b08e6bfc5a87?l=en&r=818739537&uc=app_square_share_link&us=more

**Review by Swiftyyz — COMMENTED** [review]
Approved

**Review by Swiftyyz — COMMENTED** [review]
Override

**Review by Setarland — APPROVED** [review]

**Review by adairhgf-web — APPROVED** [review]

**Pull request merged**
